### ISSUE TITLE
zoom in and out faster

### ISSUE THREAD

**Issue by LogWell** [wkjarosz/hdrview#89]
For images that are too large or too small, we need a faster scroll wheel zoom factor, the speed in [tev](https://github.com/Tom94/tev) is suitable.

**Comment by wkjarosz** [comment]
I don't want to change the default for everyone, as this depends on personal preference, but having a configurable zoom in/out speed would be a nice feature improvement. I wouldn't want to complicate the GUI with an extra widget, since this would likely need to be set rarely, but this could be accomplished by reading a setting from the user's .json settings file. I likely won't be able to get to this in the near future, so closing for now, but I'm happy to take a pull request with a change.
